version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/inventory?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    networks:
      - inventory-network

  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d inventory" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - inventory-network

volumes:
  postgres_data:


networks:
  inventory-network:
    driver: bridge
